### ISSUE TITLE
Apple silicon

### ISSUE THREAD

**Issue by luis-1979** [MUZIStudio/Gdx-Assets-Protector-Examples#1]
Hi, I'm trying the library; great work!
I have no problems on Windows but on MacOS Apple Silicon there is this error on building:

dlopen(libgdx-protector.dylib, 0x0009): tried: 'libgdx-protector.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibgdx-protector.dylib' (no such file), '/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/./libgdx-protector.dylib' (no such file), '/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/../lib/libgdx-protector.dylib' (no such file), '/usr/lib/libgdx-protector.dylib' (no such file, not in dyld cache), 'libgdx-protector.dylib' (no such file), '/usr/lib/libgdx-protector.dylib' (no such file, not in dyld cache)

Is Apple Silicon supported and am I doing something wrong, or if it isn't supported what can I do?
Thanks!

**Comment by MuziStudio** [comment]
Apologies, we currently support only Android and Windows platforms, so the dynamic libraries for Mac and iOS are unavailable. We are considering some work to visualize the encryption process and support Apple. Please continue to follow this project.

**Comment by MuziStudio** [comment]
Here is the MacOS Arm64 architecture dynamic library that I obtained through cross-compilation. Since I don't have a MacBook, I am unable to test it myself. If you find that it works after testing, please let me know, and I will make the necessary updates. If it doesn't work, please provide the error information, and I will attempt to make adjustments.[libgdx-protector.dylib](https://github.com/MUZIStudio/Gdx-Assets-Protector-Examples/blob/master/README-Res/libgdx-protector.dylib)

**Comment by luis-1979** [comment]
Thanks!!!
I will try tonight.

Luigi

Il lun 3 giu 2024, 12:54 Muzi Studio ***@***.***> ha scritto:

**Comment by luis-1979** [comment]
Hi!,
I tried putting the library in core/libs and including the *.dylib files.
Does not find dependence; did I do it right or should I do it differently?

Thanks!

The error is:
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException:
java.lang.UnsatisfiedLinkError: Unable to load library 'gdx-protector':
dlopen(libgdx-protector.dylib, 0x0009): tried: 'libgdx-protector.dylib' (no
such file), '/System/Volumes/Preboot/Cryptexes/OSlibgdx-protector.dylib'
(no such file), '/Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/./libgdx-protector.dylib' (no
such file), '/Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/../lib/libgdx-protector.dylib'
(no such file), '/usr/lib/libgdx-protector.dylib' (no such file, not in
dyld cache), 'libgdx-protector.dylib' (no such file),
'/usr/lib/libgdx-protector.dylib' (no such file, not in dyld cache)
dlopen(libgdx-protector.dylib, 0x0009): tried: 'libgdx-protector.dylib' (no
such file), '/System/Volumes/Preboot/Cryptexes/OSlibgdx-protector.dylib'
(no such file), '/Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/./libgdx-protector.dylib' (no
such file), '/Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/../lib/libgdx-protector.dylib'
(no such file), '/usr/lib/libgdx-protector.dylib' (no such file, not in
dyld cache), 'libgdx-protector.dylib' (no such file),
'/usr/lib/libgdx-protector.dylib' (no such file, not in dyld cache)
dlopen(/Users/luigi.ferraresi/Library/Frameworks/gdx-protector.framework/gdx-protector,
0x0009): tried:
'/Users/luigi.ferraresi/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file),
'/System/Volumes/Preboot/Cryptexes/OS/Users/luigi.ferraresi/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file),
'/Users/luigi.ferraresi/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file),
'/System/Library/Frameworks/gdx-protector.framework/gdx-protector' (no such
file, not in dyld cache)
dlopen(/Library/Frameworks/gdx-protector.framework/gdx-protector, 0x0009):
tried: '/Library/Frameworks/gdx-protector.framework/gdx-protector' (no such
file),
'/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file), '/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file),
'/System/Library/Frameworks/gdx-protector.framework/gdx-protector' (no such
file, not in dyld cache)
dlopen(/System/Library/Frameworks/gdx-protector.framework/gdx-protector,
0x0009): tried:
'/System/Library/Frameworks/gdx-protector.framework/gdx-protector' (no such
file),
'/System/Volumes/Preboot/Cryptexes/OS/System/Library/Frameworks/gdx-protector.framework/gdx-protector'
(no such file),
'/System/Library/Frameworks/gdx-protector.framework/gdx-protector' (no such
file, not in dyld cache)
Native library (darwin-aarch64/libgdx-protector.dylib) not found in
resource path
(/Users/luigi.ferraresi/Projects/better-dead-libgdx/desktop/build/classes/java/main:/Users/luigi.ferraresi/Projects/better-dead-libgdx/desktop/build/resources/main:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl3/1.12.1/12a144cacb34f0392cd8354f798d99e4836a51a8/gdx-backend-lwjgl3-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/5737be5ce3a4e8f9f77c2d9ab95ab479f9c3705f/gdx-platform-1.12.1-natives-desktop.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.12.1/4e82228fcdd2e8a7673fe7952588acfdb33d7820/gdx-box2d-platform-1.12.1-natives-desktop.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx-controllers/gdx-controllers-desktop/2.2.3/f496535b094461487a71b3f23a17cd7d524de0f5/gdx-controllers-desktop-2.2.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-tools/1.12.1/c0670e43a98e4602e2cda9188ce7b41b4605a215/gdx-tools-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-lwjgl3-glfw-awt-macos/1.12.1/618fd31d227fed4e11c0840802dad248bb2f615f/gdx-lwjgl3-glfw-awt-macos-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-lwjgl3-angle/1.12.1/82499f9743532b9edfd843b99a897b6016cd147a/gdx-lwjgl3-angle-1.12.1.jar:/Users/luigi.ferraresi/Projects/better-dead-libgdx/core/build/libs/core-0.0.jar:/Users/luigi.ferraresi/Projects/better-dead-libgdx/core/libs/libgdx-protector.dylib:/Users/luigi.ferraresi/Projects/better-dead-libgdx/core/libs/gdx-protector.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx-controllers/gdx-controllers-core/2.2.3/82b77d6cb6394420cdd480fc2ab373f7ba5e0e45/gdx-controllers-core-2.2.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-lwjgl/1.12.1/82ef2637694ab920beeaa8e808e33dd3c360d80f/gdx-backend-lwjgl-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype/1.12.1/d5826997b0cfa595a72889610fadb18405056c1c/gdx-freetype-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-headless/1.12.1/22b5d8ed8ad1358c63ed4ce223634d166003c70e/gdx-backend-headless-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d/1.12.1/6c37ed04f97d062f1bdc4afe1f583182e539a269/gdx-box2d-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-ai/1.8.2/ab75d2ce80ab1b1ce6828a15dc0f417abac4c674/gdx-ai-1.8.2.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.rafaskoberg.gdx/typing-label/1.3.0/88b84a3407189dfff51e4eeeca0e5993d75ca7cf/typing-label-1.3.0.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.crashinvaders.vfx/gdx-vfx-effects/0.5.4/7b8c2db8bcef15d9837fb78b7905df3df7b605f8/gdx-vfx-effects-0.5.4.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.crashinvaders.vfx/gdx-vfx-core/0.5.4/8d24024b61aa16bf7e89e0c13f59d4984edc6bb1/gdx-vfx-core-0.5.4.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.12.1/a2d066c09329c457045c284c42d6f37122840aa/gdx-1.12.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/efa1eb78c5ccd840e9f329717109b5e892d72f8e/lwjgl-glfw-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/a03684c5e4b1b1dbbe0d29dbbdc27b985b6840f2/lwjgl-glfw-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/d9af485c32545b37dd5359b163161d42d7534dcf/lwjgl-glfw-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/492a0f11f85b85899a6568f07511160c1b87cd38/lwjgl-glfw-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/a1bf400f6bc64e6195596cb1430dafda46090751/lwjgl-glfw-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/ee8cc78d0a4a5b3b4600fade6d927c9fc320c858/lwjgl-glfw-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/e449e28b4891fc423c54c85fbc5bb0b9efece67a/lwjgl-glfw-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-glfw/3.3.3/32334f3fd5270a59bad9939a93115acb6de36dcf/lwjgl-glfw-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/b543467b7ff3c6920539a88ee602d34098628be5/lwjgl-jemalloc-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/4f86728bf449b1dd61251c4e0ac01df1389cb51e/lwjgl-jemalloc-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/109b6931880d02d4e65ced38928a16e41d19873e/lwjgl-jemalloc-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/eff8b86798191192fe2cba2dc2776109f30c239d/lwjgl-jemalloc-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/2906637657a57579847238c9c72d2c4bde7083f8/lwjgl-jemalloc-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/e9412c3ff8cb3a3bad1d3f52909ad74d8a5bdad1/lwjgl-jemalloc-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/426222fc027602a5f21b9c0fe79cde6a4c7a011f/lwjgl-jemalloc-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.3.3/f6063b6e0f23be483c5c88d84ce51b39dc69126c/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/daada81ceb5fc0c291fbfdd4433cb8d9423577f2/lwjgl-openal-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/3037360cc4595079bea240af250b6d1a527e0905/lwjgl-openal-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/e1702aa09d20359d6cf5cb2999fa7685a785eca7/lwjgl-openal-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/ad8f302118a65bb8d615f8a2a680db58fb8f835e/lwjgl-openal-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/8df8338bfa77f2ebabef4e58964bd04d24805cbf/lwjgl-openal-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/c78b078de2fb52f45aa55d04db889a560f3544f/lwjgl-openal-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/cf83862ae95d98496b26915024c7e666d8ab1c8f/lwjgl-openal-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-openal/3.3.3/87b8d5050e3adb46bb58fe1cb2669a4a48fce10d/lwjgl-openal-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/2f6b0147078396a58979125a4c947664e98293a/lwjgl-opengl-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/62c70a4b00ca5391882b0f4b787c1588d24f1c86/lwjgl-opengl-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/dbba17fc5ac0985d14a57c11f9537617d67b9952/lwjgl-opengl-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/2096f6b94b2d68745d858fbfe53aacf5f0c8074c/lwjgl-opengl-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/1bd45997551ae8a28469f3a2b678f4b7289e12c0/lwjgl-opengl-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/d213ddef27637b1af87961ffa94d6b27036becc8/lwjgl-opengl-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/e6c1eec8be8a71951b830a4d69efc01c6531900c/lwjgl-opengl-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengl/3.3.3/d32d833dcaa2f355a886eaf21f0408b5f03241d/lwjgl-opengl-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/25dd6161988d7e65f71d5065c99902402ee32746/lwjgl-stb-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/fd1271ccd9d85eff2fa31f3fd543e02ccfaf5041/lwjgl-stb-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/1ae28ff044699ff29b0e980ffabd73fba8a664b3/lwjgl-stb-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/ddc177afc2be1ee8d93684b11363b80589a13fe1/lwjgl-stb-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/472792c98fb2c1557c060cb9da5fca6a9773621f/lwjgl-stb-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/51c6955571fbcdb7bb538c6aa589b953b584c6af/lwjgl-stb-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/1d9facdf6541de114b0f963be33505b7679c78cb/lwjgl-stb-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-stb/3.3.3/b5c874687b9aac1a936501d4ed2c49567fd1b575/lwjgl-stb-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/b3a29ff95bdb320122839741a3723338e6ecfa28/lwjgl-opengles-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/d59211c8746d50cfb610bd38f8d817a94fbdf013/lwjgl-opengles-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/8b0c02692d6f869dee1060f290fd157f05dfa999/lwjgl-opengles-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/af05595560d4ae6117242ca051e5ae4f27aea9e3/lwjgl-opengles-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/d6a20b1f204e48989d994923f4f5131c55424844/lwjgl-opengles-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/5aeb20635f6d20f2f7f69fe9c05cab831e574b8c/lwjgl-opengles-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/22939720fc2737b419dd52db84b8c56bcfab3aac/lwjgl-opengles-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-opengles/3.3.3/331b739ab66790449888e553052ecb051f37ad3f/lwjgl-opengles-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-egl/3.3.3/2f0d613e3f769577548f08b11ae9b7571980aeb1/lwjgl-egl-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/29589b5f87ed335a6c7e7ee6a5775f81f97ecb84/lwjgl-3.3.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/1713758e3660ba66e1e954396fd18126038b33c0/lwjgl-3.3.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/2075c51a80f0ef0f22ba616ba54007ac2b0debd4/lwjgl-3.3.3-natives-linux-arm32.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/f35d8b6ffe1ac1e3a5eb1d4e33de80f044ad5fd8/lwjgl-3.3.3-natives-linux-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/33a6efa288390490ce6eb6c3df47ac21ecf648cf/lwjgl-3.3.3-natives-macos.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/226246e75f6bd8d4e1895bdce8638ef87808d114/lwjgl-3.3.3-natives-macos-arm64.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/a5ed18a2b82fc91b81f40d717cb1f64c9dcb0540/lwjgl-3.3.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl/3.3.3/9e670718e050aeaeea0c2d5b907cffb142f2e58f/lwjgl-3.3.3-natives-windows-x86.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.jlayer/jlayer/1.0.1-gdx/7cca83cec5c1b2f011362f4d85aabd71a73b049d/jlayer-1.0.1-gdx.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.jcraft/jorbis/0.0.17/8872d22b293e8f5d7d56ff92be966e6dc28ebdc6/jorbis-0.0.17.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.jamepad/jamepad/
2.0.20.0/55eb0007fd55c9914d106dac3387b9d444572cab/jamepad-2.0.20.0.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.code-disaster.steamworks4j/steamworks4j/1.10.0-SNAPSHOT/ee37db96e04871a4dbe1298eed3b9e3ab38ec907/steamworks4j-1.10.0-SNAPSHOT.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-jnigen-loader/2.3.1/2d472f69243631fbcb3d4c3f93dd2e137a6cb084/gdx-jnigen-loader-2.3.1.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/com.github.tommyettinger/regexodus/0.1.13/6b983171efabe725ed29de22e328ef37b7ebd68e/regexodus-0.1.13.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.3/fbc2afb3e288578e9942578decb6291a490549a0/lwjgl-platform-2.9.3-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.3/b1eafe80093381c56415731e1d64279e6140bcd0/lwjgl-platform-2.9.3-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl-platform/2.9.3/6686cf6ddaa20b4290aa6599a09bc0d17369be05/lwjgl-platform-2.9.3-natives-osx.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput/2.0.5/39c7796b469a600f72380316f6b1f11db6c2c7c4/jinput-2.0.5.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/net.java.jutils/jutils/1.0.0/e12fe1fda814bd348c1579329c86943d2cd3c6a6/jutils-1.0.0.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/7ff832a6eb9ab6a767f1ade2b548092d0fa64795/jinput-platform-2.0.5-natives-linux.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/385ee093e01f587f30ee1c8a2ee7d408fd732e16/jinput-platform-2.0.5-natives-windows.jar:/Users/luigi.ferraresi/.gradle/caches/modules-2/files-2.1/net.java.jinput/jinput-platform/2.0.5/53f9c919f34d2ca9de8c51fc4e1e8282029a9232/jinput-platform-2.0.5-natives-osx.jar
)
at
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:173)

Il giorno lun 3 giu 2024 alle ore 18:10 Luigi Ferraresi <
***@***.***> ha scritto:

**Comment by MuziStudio** [comment]
Place the *.dylib library in the location specified by the error message, or in the same directory as the *.jar files (on Windows, this would be a *.dll file; the principle is similar), or in any directory that is considered by the Java function System.load, so that the library file can at least be recognized as existing. I am not very familiar with Mac systems, so this is just for reference.
